server:
  port: 6001
  
spring:
  redis:
    host: 192.168.1.218
    port: 6379
    database: 2

netty: 
  order:  
    server: 
      host: 192.168.1.209
      port: 6002
  central:  
    server: 
      host: 192.168.1.186
      port: 7002
