server:
  port: 8001
  

netty: 
  central:  
    server: 
      host: 192.168.1.186
      port: 7002
  order:  
    server: 
      host: 192.168.1.186
      port: 6002
  market: 
    server: 
      host: 222.73.119.230
      port: 9011  
  